version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  order-service:
    build:
      context: ./microservices/OrderService
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - kafka
      - eureka-server
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - EUREKA_SERVER=http://eureka-server:8761/eureka/

  cart-service:
    build:
      context: ./microservices/CartService
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - eureka-server
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - EUREKA_SERVER=http://eureka-server:8761/eureka/

  payment-service:
    build:
      context: ./microservices/PaymentService
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - kafka
      - eureka-server
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - EUREKA_SERVER=http://eureka-server:8761/eureka/

  inventory-service:
    build:
      context: ./microservices/inventoryService
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - kafka
      - eureka-server
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - EUREKA_SERVER=http://eureka-server:8761/eureka/

  eureka-server:
    build:
      context: ./Infrastructure/EurekaServer
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - EUREKA_SERVER_ENABLED=true
